### ISSUE TITLE
New mint namespace resources do not resolve

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/rdf_explorer#15]
Example: https://w3id.org/okn/i/mint/pihm-v2

**Comment by sirspock** [comment]
Fixed it. Please, remove w3id redirect.

```
➜  ~ curl -L -H "Host: w3id.org" -H "Accept: text/turtle" http://localhost:7070/okn/i/mint/mintproject/pihm:v2
@prefix mint:  <https://w3id.org/mint/instance/> .
@prefix ccut:  <https://www.w3id.org/mint/ccut#> .
@prefix qudtp: <http://qudt.org/1.1/schema/qudt#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml:   <http://www.w3.org/XML/1998/namespace> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns2:   <https://schema.org/> .
@prefix ns1:   <http://www.geoscienceontology.org/svo/svu#> .
@prefix ns3:   <http://www.w3.org/2004/02/skos/core#> .

<https://w3id.org/okn/i/mint/mintproject/pihm:v2>
        a       <https://w3id.org/okn/o/sd#SoftwareImage> .
```

![Screen Shot 2019-07-19 at 12 06 23 PM](https://user-images.githubusercontent.com/2365990/61549419-f30d0100-aa1d-11e9-8c21-a686a316e29c.png)

**Comment by dgarijo** [comment]
Where should I redirect the w3id? http://ontosoft.isi.edu:7070/okn/i/mint/PIHM does not work.
My current rewrite rule for the /mint/instance/ is:
RewriteRule ^(.*) http://ontosoft.isi.edu:7070/mint/instance/$1 [R=302,L] 

For /okn/i/ it should be something like:
RewriteRule ^(.*) http://ontosoft.isi.edu:7070/okn/i/$1 [R=302,L]
Also, right now the new version is living in the /dev/ graph
