### ISSUE TITLE
Ontology

### ISSUE THREAD

**Issue by sirspock** [KnowledgeCaptureAndDiscovery/rdf_explorer#5]
Where I can find the opmw ontology? http://www.opmw.org/ontology/WorkflowExecutionAccount

**Comment by dgarijo** [comment]
Sigh. Redirection is broken. Here is the doc:
http://www.opmw.org/model/OPMW/

Can you please fix the redirect? We should talk about this.

**Comment by dgarijo** [comment]
Also, I want to push a new version of the ontology. Maybe I need to create
a repo... Thoughts?

**Comment by sirspock** [comment]
Yes, the repository must be similar to MINT-ModelCatalog https://mintproject.github.io/Mint-ModelCatalog-Ontology/modelCatalog/release/0.3.0/index-en.html#hasPresentation

**Comment by sirspock** [comment]
About the repository:
name: OPMW-Model
org: KnowledgeCaptureAndDiscovery
Right?

**Comment by sirspock** [comment]
Redirect ok:
```
    Rewriterule ontology/(.+)  "model/OPMW/#$1" [NE,R,L]
```

**Comment by dgarijo** [comment]
Thanks. Will work on the repo soon

**Comment by dgarijo** [comment]
This issue seems to be addressed
