### ISSUE TITLE
Fix prefixes

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/rdf_explorer#9]
Some of the prefixes defined are not correct (e.g., purl for dc).
It would be great if there was a file where I could define additional prefixes.

- [x] purl

**Comment by sirspock** [comment]
We can the prefix using a configuration file. Do you like it?

**Comment by dgarijo** [comment]
yes, let's do that.

**Comment by dgarijo** [comment]
Also, can we use a config file that is quite generic? I would like to be able to edit it here instead of wherever the service is deployed. Thanks!
